# Site settings
title: Ingest In Love
email: morgan.jones1726@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Ingest in Love. Organic Placenta Ecapsulation services for the DFW area"
keywords: "placenta encapsulation, DFW placenta encapsulation"
skills: "Organic Placenta Ecapsulation  - Organic Tincture"
meta_author: Jones Morgan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fba2ba #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: c98686 #FD6E8A
  secondary-dark: 000000 #A2122F

# Footer settings
footer:
  copyright: Ingest In Love
  location: Location
  social: Around the Web
  credits: Sister Services

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: DFW Area
  # - line: Beverly Hills, CA 90210

# Credits content
credits: Eve the Doula

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
